//
// Copyright (c) 2016 Tapjoy, Inc.
// All rights reserved.
//

//
// DO NOT EDIT THIS FILE.
//

using UnityEngine;

namespace TapjoyUnity.Internal {

  public sealed class TapjoyUnityInit : MonoBehaviour {

    void Awake() {
      #if UNITY_EDITOR
      #elif UNITY_ANDROID
      ApiBindingAndroid.Install();
      #elif UNITY_IOS
      ApiBindingIos.Install();
      #endif
    }
  }
}
